### PR TITLE
Add Replicate demo and API

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @sczhou  ! 👋 

We are impressed how well your model works, especially improving the stable-diffusion generated images!

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can run your model! View it here: https://replicate.com/cjwbw/codeformer

Replicate also have an API, so people can easily run your model from their code:

```python
import replicate
model = replicate.models.get("cjwbw/codeformer")
output = model.predict(image="...")
```

You are more than welcome to modify the Replicate page (e.g. [Example](https://replicate.com/cjwbw/codeformer/examples) Gallery), let me know and I can transfer ownership to your Replicate account.

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by sczhou** [comment]
Hi @chenxwh Thanks for your effort to make this demo. The demo looks great! :+1: 

I'm wondering if I can modify the overview and example pages in Replicate. I'd also like to know how to update demos on it since we will have some new models for face and background image enhancement. If needed, could you help transfer this ownership to my Replicate account? 

Thanks :-)

**Comment by chenxwh** [comment]
Hi @sczhou,

Glad you like the demo!
The page is now under your account: https://replicate.com/sczhou/codeformer. You should now be able to change the examples, front page of the demo!

To upload new versions, you will need to have [Cog](https://github.com/replicate/cog) installed, then on terminal 
`cog login` -> after the authentication you will have the permission to your demo page
`cog push r8.im/sczhou/codeformer`  -> this will update the demo on replicate accordingly
Make sure you have all the files (weights etc. prepared when you push the image for speedy inference)

Since there is already a working version on replicate, maybe it is easier to pull the image and make changes accordingly, please refer to [these steps](https://github.com/gwang-kim/DiffusionCLIP/pull/15#issuecomment-1211737126) as an example of how to do it.

More documentation about Cog can be found [here](https://github.com/replicate/cog).

Let me know if you need further clarification :)

**Comment by sczhou** [comment]
Hi @chenxwh,

Thanks for your help! CodeFormer runs smoothly with this online demo 👍 

I will then modify the overview page in Replicate, and merge this PR :-)

**Comment by sczhou** [comment]
Hi @chenxwh, 

When I choose another showcase from my own testing, there are some link errors. The errors could appear in the following places:
1. https://replicate.com/explore
image

2. https://replicate.com/sczhou
image

3. https://replicate.com/sczhou/codeformer
image

---

I checked all three errors should be caused by wrong links,  e.g.,
`/api/models/sczhou/codeformer/files/https://replicate.com/api/models/sczhou/codeformer/files/dbccb795-25f8-4cd1-a43a-ed222572a7a5/output.png`
should be:
`/api/models/sczhou/codeformer/files/dbccb795-25f8-4cd1-a43a-ed222572a7a5/output.png`

image

I don't know how to fix this link error, could you help me with that? 

Many thanks! 😄

**Comment by sczhou** [comment]
Hi @chenxwh, 

I check the output path in the `predict.py` file, which should be accurate. And I push the model again, but the link error still exists. Could you have a look at this error?

**Comment by chenxwh** [comment]
Hi @sczhou sorry for the late response and thanks for reporting the issue. Just to confirm you are using the same `predict.py` or any update?
@andreasjansson could you have a look at this?

I also report the issue [here](https://github.com/replicate/cog/issues/718)

**Comment by sczhou** [comment]
Thanks @chenxwh, I reported this [issue](https://github.com/replicate/cog/issues/717) in Cog repo as well.

I didn't make substantial modifications in my pushed version, the output path is the same. Actually, this error occurs after you move this page under my account (before I push), I pushed the model again since I think it could be a solution.

**Comment by chenxwh** [comment]
It is fixed now :)

**Comment by sczhou** [comment]
Great! Thanks @chenxwh :-)

**Pull request merged**
